### ISSUE TITLE
Suggestions for app options

### ISSUE THREAD

**Issue by stsewd** [DougBeney/pickachu#5]
Hi, awesome plugin I think I going to use it a lot, especially the date picker :)

Would be nice to have suggestions for the apps after the :Pickachu command (with tab).

**Comment by DougBeney** [comment]
Hi, stsewd!
Really glad you like it. :D

Yeah, that's a good idea.

Perhaps next release I could add this feature with the addition of a help menu - `:Help Pickachu`.

**Comment by DougBeney** [comment]
Fixed in f4c68eb64d03d6d49ba3616870ea9601f7d1c21b

**Comment by stsewd** [comment]
@DougBeney This issue isn't solved, the another PR was about defining a default command, this one is about have completions with `<tab>` :)

**Comment by DougBeney** [comment]
My bad. Pulled the trigger too fast there!
